### ISSUE TITLE
build `jenkins-contribution-aggregator` instead of `jenkins-top-contributor`

### ISSUE THREAD

**Issue by jmMeessen** [jmMeessen/jenkins-top-submitters#37]
With the move of the application to the jenkins-infra org, the repository application has also been renamed. For tidyness, this implies that the executable has to be rename.

```[tasklist]
### Tasks
- [x] Rename main file to `jenkins-contribution-aggregator`
- [x] update make file
- [x] update goReleaser
- [x] test release process
- [x] test codecoverage
```

**Comment by jmMeessen** [comment]
The required changes have been performed 👍
